name: Rebase Pull Request

on:
  repository_dispatch:
    types: [ rebase-command ]

#concurrency:
#  group: "rebase-${{ github.event.number }}"
#  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rebase_pull_request:
    name: Rebase Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Rebase Pull Request
        uses: peter-evans/rebase@08cedbbd4eabcd913bf091844614eceddaea4a5d
        id: rebase
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.event.client_payload.pull_request.head.label }}

      - name: Add 👍 Reaction
        if: always() && steps.rebase.outputs.rebased-count == 1
        uses: peter-evans/create-or-update-comment@2ef7be1cfae84b02f7b4e47ce45c1f93762d1d92
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: '+1'

      - name: Add 👎 Reaction
        if: always() && steps.rebase.outputs.rebased-count != 1
        uses: peter-evans/create-or-update-comment@2ef7be1cfae84b02f7b4e47ce45c1f93762d1d92
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: '-1'
